### ISSUE TITLE
compatibility with tensoRF

### ISSUE THREAD

**Issue by emjay73** [nianticlabs/nerf-object-removal#10]
Thank you for sharing the code.

I'm trying to train the tensoRF as the basemodel on nerf-object-removal dataset.

I noticed that there are unpleasant floaters around the suspected aabb box region.

https://github.com/nianticlabs/nerf-object-removal/assets/36818801/e6829e31-3873-4105-8969-e764fca9673a

Did you also observe the same phenomenon using the NeRF basemodel?

If not, any suggestions?

I ran the code after changing the following settings.

self.near_far = [0.1,6.0]
self.scene_bbox = torch.tensor([[-1., -1., -1.], [1., 1., 1.]])

**Comment by weders** [comment]
Hi, what is very important to get rid of the floaters is to have all the regularizers for the density. Further, it also helps to visualize the training images and the closest training view for each test view.
