### ISSUE TITLE
Can't find requirements_v2.txt

### ISSUE THREAD

**Issue by Shiva-Gantha** [nianticlabs/nerf-object-removal#4]
Cannot find the requirements_v2.txt file as on line : https://github.com/nianticlabs/nerf-object-removal/blob/b284200d016f74d19125d0ad199ebeb3b571b050/install.sh#L17

**Comment by amonszpart** [comment]
Hi,

Thanks for your interest, apologies for the mistake.
I've opened a [PR](https://github.com/nianticlabs/nerf-object-removal/pull/5) for getting that file merged, you can find it here for now: https://github.com/nianticlabs/nerf-object-removal/blob/aron/pip-fix/requirements_v2.txt

Thanks,
Aron

**Comment by Shiva-Gantha** [comment]
Thanks a lot, I appreciate your prompt reply!
Also, I am facing installation issues due to dependency conflicts:
`orbax 0.1.7 requires jax>=0.4.6, but you have jax 0.3.20 which is incompatible.
oryx 0.2.4 requires jax==0.3.21, but you have jax 0.3.20 which is incompatible.
oryx 0.2.4 requires jaxlib==0.3.20, but you have jaxlib 0.3.15+cuda11.cudnn82 which is incompatible.`

I am following the installation instructions as mentioned in README.md, could you please help with how could I resolve it?

Thanks!

**Comment by HannahHaensen** [comment]
@Shiva-Gantha Hey could you resolve the issue? I also tried to use the Docker but I have the same issues?

**Comment by weders** [comment]
Thank you for your patience, just opened a pull request that should fix  the issue. It seems the main issue is here:

FileNotFoundError: [Errno 2] No such file or directory: '/app/object-removal/experiments/real/001/data/../transforms_train.json'

This should fix this for now. What is important to note. Currently, it needs CUDA 11.1 as for other versions the required JAX version might not work.
