### ISSUE TITLE
Code Run Error

### ISSUE THREAD

**Issue by aiyb1314** [nianticlabs/nerf-object-removal#9]
AttributeError: module 'tensorflow.python.framework.type_spec' has no attribute '_NAME_TO_TYPE_SPEC'
Could you tell me the version of tensorflow.

**Comment by ericyangchen** [comment]
@weders thank you for the code.
But I've encountered the same error when running `./test_real.sh` (evaluation).
Could you please look into this issue. Much thanks!

The error msg: `AttributeError: module 'tensorflow.python.framework.type_spec' has no attribute '_NAME_TO_TYPE_SPEC'`

I suspect this is related to the version of `oynx` and `tensorflow-probability`. I've noticed some incompatibility issues when installing packages.

**Comment by ericyangchen** [comment]
Also, @aiyb1314 have you resolved the issue? I would appreciate some guiding if you've fixed it already. Thank you.

**Comment by weders** [comment]
This is fixed with this PR #14 .
